-- Substitui os tópicos aproximados do seed inicial (0002) pela numeração
-- oficial do edital (supabase/edital.odt), com Unidades onde o item do
-- edital tem 2+ subitens (ex: "6 Planos de amortização" -> unidade com
-- 6.1/6.2/6.3 como tópicos) e itens de 3º nível dobrados no nome do
-- tópico pai entre parênteses (schema só suporta 2 níveis abaixo da
-- disciplina). Gerado por scratchpad/parse_edital.py + gerar_sql_edital.py
-- a partir da conversão de edital.odt.
--
-- JÁ APLICADO no banco em produção em 2026-08-30: 48 unidades, 289 tópicos.

BEGIN;

-- limpa conteudos e unidades antigos do concurso sefaz-al (mantém grupos/disciplinas)
DELETE FROM conteudos WHERE disciplina_id IN (
  SELECT d.id FROM disciplinas d JOIN grupos g ON g.id=d.grupo_id JOIN concursos c ON c.id=g.concurso_id WHERE c.slug='sefaz-al'
);
DELETE FROM unidades WHERE disciplina_id IN (
  SELECT d.id FROM disciplinas d JOIN grupos g ON g.id=d.grupo_id JOIN concursos c ON c.id=g.concurso_id WHERE c.slug='sefaz-al'
);

WITH disc AS (
  SELECT d.id, d.nome FROM disciplinas d
  JOIN grupos g ON g.id = d.grupo_id
  JOIN concursos c ON c.id = g.concurso_id
  WHERE c.slug = 'sefaz-al'
),
u AS (
  INSERT INTO unidades (disciplina_id, nome)
  SELECT disc.id, x.nome FROM disc JOIN (VALUES
    ('MATEMÁTICA FINANCEIRA', '6 Planos de amortização de empréstimos e financiamentos.'),
    ('DIREITO CONSTITUCIONAL', '2 Aplicabilidade das normas constitucionais.'),
    ('DIREITO CONSTITUCIONAL', '7 Poder Legislativo.'),
    ('DIREITO CONSTITUCIONAL', '9 Funções essenciais à justiça.'),
    ('DIREITO CONSTITUCIONAL', '10 Controle de constitucionalidade.'),
    ('DIREITO ADMINISTRATIVO', '1 Estado, governo e administração pública.'),
    ('DIREITO ADMINISTRATIVO', '2 Direito administrativo.'),
    ('DIREITO ADMINISTRATIVO', '3 Ato administrativo.'),
    ('DIREITO ADMINISTRATIVO', '4 Agentes públicos.'),
    ('DIREITO ADMINISTRATIVO', '5 Poderes da administração pública.'),
    ('DIREITO ADMINISTRATIVO', '6 Regime jurídico administrativo.'),
    ('DIREITO ADMINISTRATIVO', '7 Responsabilidade civil do Estado.'),
    ('DIREITO ADMINISTRATIVO', '8 Serviços públicos.'),
    ('DIREITO ADMINISTRATIVO', '9 Organização administrativa.'),
    ('DIREITO ADMINISTRATIVO', '10 Controle da administração pública.'),
    ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.'),
    ('ESTATÍSTICA E PROBABILIDADE', '3 Probabilidade.'),
    ('CONTABILIDADE PÚBLICA', '2 Patrimônio público.'),
    ('CONTABILIDADE PÚBLICA', '3 Variações patrimoniais.'),
    ('CONTABILIDADE PÚBLICA', '4 Mensuração de ativos.'),
    ('CONTABILIDADE PÚBLICA', '5 Mensuração de passivos.'),
    ('CONTABILIDADE PÚBLICA', '7 Sistema de custos.'),
    ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.'),
    ('FINANÇAS PÚBLICAS', '1 Finanças públicas: conceitos, objetivos, metas e abrangência.'),
    ('FINANÇAS PÚBLICAS', '2 Política econômica e fiscal.'),
    ('FINANÇAS PÚBLICAS', '3 Orçamento público.'),
    ('FINANÇAS PÚBLICAS', '4 Orçamento público no Brasil.'),
    ('FINANÇAS PÚBLICAS', '5 Programação e execução orçamentária e financeira.'),
    ('FINANÇAS PÚBLICAS', '7 Despesa pública: conceito, classificações e estágios.'),
    ('FINANÇAS PÚBLICAS', '8 Responsabilidade e controle fiscal.'),
    ('FINANÇAS PÚBLICAS', '9 Fluxo de caixa.'),
    ('FINANÇAS PÚBLICAS', '10 Moeda, crédito e Sistema Financeiro Nacional.'),
    ('FINANÇAS PÚBLICAS', '12 Mercado financeiro brasileiro.'),
    ('INTELIGÊNCIA ARTIFICIAL', '6 Inteligência artificial generativa.'),
    ('DESENVOLVIMENTO DE SISTEMAS', '1 Modelagem de processos de negócio.'),
    ('DESENVOLVIMENTO DE SISTEMAS', '4 Arquitetura de software.'),
    ('DESENVOLVIMENTO DE SISTEMAS', '7 Desenvolvimento.'),
    ('DESENVOLVIMENTO DE SISTEMAS', '9 Segurança no desenvolvimento.'),
    ('DESENVOLVIMENTO DE SISTEMAS', '10 Conceitos avançados em engenharia e arquitetura de software.'),
    ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '1 Infraestrutura em nuvem.'),
    ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '3 Gestão de serviços.'),
    ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '4 Forense computacional.'),
    ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '5 Redes de computadores.'),
    ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.'),
    ('CIÊNCIA DE DADOS', '1 Dado, informação, conhecimento e inteligência.'),
    ('CIÊNCIA DE DADOS', '3 Bancos de dados relacionais.'),
    ('CIÊNCIA DE DADOS', '6 Processo de ciência de dados.'),
    ('CIÊNCIA DE DADOS', '8 Mineração de dados.')
  ) AS x(disciplina_nome, nome) ON upper(x.disciplina_nome) = upper(disc.nome)
  RETURNING id, nome, disciplina_id
)
INSERT INTO conteudos (disciplina_id, unidade_id, nome)
SELECT disc.id, u.id, x.nome
FROM disc
JOIN u ON u.disciplina_id = disc.id
JOIN (VALUES
  ('MATEMÁTICA FINANCEIRA', '6 Planos de amortização de empréstimos e financiamentos.', '6.1 Sistema francês (tabela Price).'),
  ('MATEMÁTICA FINANCEIRA', '6 Planos de amortização de empréstimos e financiamentos.', '6.2 Sistema de amortização constante (SAC).'),
  ('MATEMÁTICA FINANCEIRA', '6 Planos de amortização de empréstimos e financiamentos.', '6.3 Sistema de amortização misto (SAM).'),
  ('DIREITO CONSTITUCIONAL', '2 Aplicabilidade das normas constitucionais.', '2.1 Normas de eficácia plena, contida e limitada.'),
  ('DIREITO CONSTITUCIONAL', '2 Aplicabilidade das normas constitucionais.', '2.2 Normas programáticas.'),
  ('DIREITO CONSTITUCIONAL', '7 Poder Legislativo.', '7.1 Estrutura.'),
  ('DIREITO CONSTITUCIONAL', '7 Poder Legislativo.', '7.2 Funcionamento e atribuições.'),
  ('DIREITO CONSTITUCIONAL', '7 Poder Legislativo.', '7.3 Processo legislativo (7.3.1 Processo legislativo federal: conceito, espécies normativas, modalidades, fases; 7.3.2 Processo legislativo estadual, distrital e municipal: normas constitucionais federais aplicáveis)'),
  ('DIREITO CONSTITUCIONAL', '7 Poder Legislativo.', '7.4 Fiscalização contábil, financeira e orçamentária.'),
  ('DIREITO CONSTITUCIONAL', '7 Poder Legislativo.', '7.5 Comissões parlamentares de inquérito.'),
  ('DIREITO CONSTITUCIONAL', '9 Funções essenciais à justiça.', '9.1 Ministério Público, advocacia pública.'),
  ('DIREITO CONSTITUCIONAL', '9 Funções essenciais à justiça.', '9.2 Advocacia privada e Defensoria Pública.'),
  ('DIREITO CONSTITUCIONAL', '10 Controle de constitucionalidade.', '10.1 Controle judicial de constitucionalidade: conceito, histórico, sistemas, pressupostos, modalidades, órgãos competentes, sujeitos legitimados, objetos de controle, tipos de inconstitucionalidade, parâmetros de controle, formalidades, procedimentos, julgamentos, decisões, efeitos das decisões, técnicas de decisão, segurança e estabilidade das decisões.'),
  ('DIREITO CONSTITUCIONAL', '10 Controle de constitucionalidade.', '10.2 Súmula vinculante.'),
  ('DIREITO CONSTITUCIONAL', '10 Controle de constitucionalidade.', '10.3 Reclamação constitucional.'),
  ('DIREITO CONSTITUCIONAL', '10 Controle de constitucionalidade.', '10.4 Controle não judicial de constitucionalidade: órgãos, institutos e procedimentos.'),
  ('DIREITO CONSTITUCIONAL', '10 Controle de constitucionalidade.', '10.5 Controle de constitucionalidade nos estados e no Distrito Federal.'),
  ('DIREITO ADMINISTRATIVO', '1 Estado, governo e administração pública.', '1.1 Conceitos.'),
  ('DIREITO ADMINISTRATIVO', '1 Estado, governo e administração pública.', '1.2 Elementos.'),
  ('DIREITO ADMINISTRATIVO', '2 Direito administrativo.', '2.1 Conceito.'),
  ('DIREITO ADMINISTRATIVO', '2 Direito administrativo.', '2.2 Objeto.'),
  ('DIREITO ADMINISTRATIVO', '2 Direito administrativo.', '2.3 Fontes.'),
  ('DIREITO ADMINISTRATIVO', '3 Ato administrativo.', '3.1 Conceito, requisitos, atributos, classificação e espécies.'),
  ('DIREITO ADMINISTRATIVO', '3 Ato administrativo.', '3.2 Extinção do ato administrativo (3.2.1 Cassação, anulação, revogação e convalidação)'),
  ('DIREITO ADMINISTRATIVO', '3 Ato administrativo.', '3.3 Decadência administrativa.'),
  ('DIREITO ADMINISTRATIVO', '4 Agentes públicos.', '4.1 Disposições constitucionais aplicáveis.'),
  ('DIREITO ADMINISTRATIVO', '4 Agentes públicos.', '4.2 Disposições doutrinárias (4.2.1 Conceito; 4.2.2 Espécies; 4.2.3 Cargo, emprego e função pública; 4.2.4 Provimento; 4.2.5 Vacância; 4.2.6 Efetividade, estabilidade e vitaliciedade; 4.2.7 Remuneração; 4.2.8 Direitos e deveres; 4.2.9 Responsabilidade; 4.2.10 Processo administrativo disciplinar)'),
  ('DIREITO ADMINISTRATIVO', '5 Poderes da administração pública.', '5.1 Hierárquico, disciplinar, regulamentar e de polícia.'),
  ('DIREITO ADMINISTRATIVO', '5 Poderes da administração pública.', '5.2 Uso e abuso do poder.'),
  ('DIREITO ADMINISTRATIVO', '6 Regime jurídico administrativo.', '6.1 Conceito.'),
  ('DIREITO ADMINISTRATIVO', '6 Regime jurídico administrativo.', '6.2 Princípios expressos e implícitos da administração pública.'),
  ('DIREITO ADMINISTRATIVO', '7 Responsabilidade civil do Estado.', '7.1 Evolução histórica.'),
  ('DIREITO ADMINISTRATIVO', '7 Responsabilidade civil do Estado.', '7.2 Responsabilidade civil do Estado no direito brasileiro (7.2.1 Responsabilidade por ato comissivo do Estado; 7.2.2 Responsabilidade por omissão do Estado)'),
  ('DIREITO ADMINISTRATIVO', '7 Responsabilidade civil do Estado.', '7.3 Requisitos para a demonstração da responsabilidade do Estado.'),
  ('DIREITO ADMINISTRATIVO', '7 Responsabilidade civil do Estado.', '7.4 Causas excludentes e atenuantes da responsabilidade do Estado.'),
  ('DIREITO ADMINISTRATIVO', '7 Responsabilidade civil do Estado.', '7.5 Reparação do dano.'),
  ('DIREITO ADMINISTRATIVO', '7 Responsabilidade civil do Estado.', '7.6 Direito de regresso.'),
  ('DIREITO ADMINISTRATIVO', '8 Serviços públicos.', '8.1 Conceito.'),
  ('DIREITO ADMINISTRATIVO', '8 Serviços públicos.', '8.2 Elementos constitutivos.'),
  ('DIREITO ADMINISTRATIVO', '8 Serviços públicos.', '8.3 Formas de prestação e meios de execução.'),
  ('DIREITO ADMINISTRATIVO', '8 Serviços públicos.', '8.4 Delegação (8.4.1 Concessão, permissão e autorização)'),
  ('DIREITO ADMINISTRATIVO', '8 Serviços públicos.', '8.5 Classificação.'),
  ('DIREITO ADMINISTRATIVO', '8 Serviços públicos.', '8.6 Princípios.'),
  ('DIREITO ADMINISTRATIVO', '9 Organização administrativa.', '9.1 Centralização, descentralização, concentração e desconcentração.'),
  ('DIREITO ADMINISTRATIVO', '9 Organização administrativa.', '9.2 Administração direta e indireta.'),
  ('DIREITO ADMINISTRATIVO', '9 Organização administrativa.', '9.3 Autarquias, fundações, empresas públicas e sociedades de economia mista.'),
  ('DIREITO ADMINISTRATIVO', '9 Organização administrativa.', '9.4 Entidades paraestatais e terceiro setor (9.4.1 Serviços sociais autônomos, entidades de apoio, organizações sociais, organizações da sociedade civil de interesse público)'),
  ('DIREITO ADMINISTRATIVO', '10 Controle da administração pública.', '10.1 Controle exercido pela administração pública.'),
  ('DIREITO ADMINISTRATIVO', '10 Controle da administração pública.', '10.2 Controle judicial.'),
  ('DIREITO ADMINISTRATIVO', '10 Controle da administração pública.', '10.3 Controle legislativo.'),
  ('DIREITO ADMINISTRATIVO', '10 Controle da administração pública.', '10.4 Improbidade administrativa (10.4.1 Lei nº 8.429/1992 e suas alterações)'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.1 Legislação pertinente (12.1.1 Lei nº 14.133/2021; 12.1.2 Decreto nº 11.462/2013 e suas alterações (Sistema de registro de preços))'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.2 Fundamentos constitucionais.'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.3 Elaboração e fiscalização de contratos.'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.4 Elaboração de projetos básicos para contratação de bens e serviços.'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.5 Critérios de remuneração por esforço versus produto.'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.6 Cláusulas e indicadores de nível de serviço.'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.7 Papel do fiscalizador do contrato.'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.8 Acompanhamento da execução contratual.'),
  ('DIREITO ADMINISTRATIVO', '12 Licitações e contratos administrativos.', '12.9 Definição e aplicação de penalidades e sanções administrativas.'),
  ('ESTATÍSTICA E PROBABILIDADE', '3 Probabilidade.', '3.1 Definições básicas e axiomas.'),
  ('ESTATÍSTICA E PROBABILIDADE', '3 Probabilidade.', '3.2 Probabilidade condicional e independência.'),
  ('CONTABILIDADE PÚBLICA', '2 Patrimônio público.', '2.1 Ativo.'),
  ('CONTABILIDADE PÚBLICA', '2 Patrimônio público.', '2.2 Passivo.'),
  ('CONTABILIDADE PÚBLICA', '2 Patrimônio público.', '2.3 Saldo patrimonial.'),
  ('CONTABILIDADE PÚBLICA', '3 Variações patrimoniais.', '3.1 Qualitativas.'),
  ('CONTABILIDADE PÚBLICA', '3 Variações patrimoniais.', '3.2 Quantitativas (3.2.1 Receita e despesa sob o enfoque patrimonial)'),
  ('CONTABILIDADE PÚBLICA', '3 Variações patrimoniais.', '3.3 Realização da variação patrimonial.'),
  ('CONTABILIDADE PÚBLICA', '3 Variações patrimoniais.', '3.4 Resultado patrimonial.'),
  ('CONTABILIDADE PÚBLICA', '4 Mensuração de ativos.', '4.1 Ativo imobilizado.'),
  ('CONTABILIDADE PÚBLICA', '4 Mensuração de ativos.', '4.2 Ativo intangível.'),
  ('CONTABILIDADE PÚBLICA', '4 Mensuração de ativos.', '4.3 Reavaliação e redução ao valor recuperável.'),
  ('CONTABILIDADE PÚBLICA', '4 Mensuração de ativos.', '4.4 Depreciação, amortização e exaustão.'),
  ('CONTABILIDADE PÚBLICA', '5 Mensuração de passivos.', '5.1 Provisões.'),
  ('CONTABILIDADE PÚBLICA', '5 Mensuração de passivos.', '5.2 Passivos contingentes.'),
  ('CONTABILIDADE PÚBLICA', '7 Sistema de custos.', '7.1 Aspectos legais do sistema de custos.'),
  ('CONTABILIDADE PÚBLICA', '7 Sistema de custos.', '7.2 Ambiente da informação de custos.'),
  ('CONTABILIDADE PÚBLICA', '7 Sistema de custos.', '7.3 Características da informação de custos.'),
  ('CONTABILIDADE PÚBLICA', '7 Sistema de custos.', '7.4 Terminologia de custos.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.1 Balanço orçamentário.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.2 Balanço financeiro.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.3 Demonstração das variações patrimoniais.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.4 Balanço patrimonial.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.5 Demonstração dos fluxos de caixa.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.6 Demonstração das mutações do patrimônio líquido.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.7 Notas explicativas às demonstrações contábeis.'),
  ('CONTABILIDADE PÚBLICA', '9 Demonstrações Contábeis Aplicadas ao Setor Público – DCASP.', '9.8 Consolidação das demonstrações contábeis.'),
  ('FINANÇAS PÚBLICAS', '1 Finanças públicas: conceitos, objetivos, metas e abrangência.', '1.1 Funções do Estado e função de bem-estar.'),
  ('FINANÇAS PÚBLICAS', '1 Finanças públicas: conceitos, objetivos, metas e abrangência.', '1.2 Políticas alocativas, distributivas e de estabilização.'),
  ('FINANÇAS PÚBLICAS', '1 Finanças públicas: conceitos, objetivos, metas e abrangência.', '1.3 Financiamento dos gastos públicos, tributação e equidade.'),
  ('FINANÇAS PÚBLICAS', '1 Finanças públicas: conceitos, objetivos, metas e abrangência.', '1.4 Tipos de tributos; progressividade, regressividade e neutralidade.'),
  ('FINANÇAS PÚBLICAS', '2 Política econômica e fiscal.', '2.1 Instrumentos das políticas fiscal, regulatória e monetária.'),
  ('FINANÇAS PÚBLICAS', '2 Política econômica e fiscal.', '2.2 Equilíbrio orçamentário, estabilização da moeda, pleno emprego, desenvolvimento econômico e redistribuição da renda.'),
  ('FINANÇAS PÚBLICAS', '2 Política econômica e fiscal.', '2.3 Déficit público: conceito, mensuração, financiamento e sustentabilidade da política fiscal.'),
  ('FINANÇAS PÚBLICAS', '2 Política econômica e fiscal.', '2.4 Crédito público como fonte de financiamento e seus limites.'),
  ('FINANÇAS PÚBLICAS', '2 Política econômica e fiscal.', '2.5 Dívida pública.'),
  ('FINANÇAS PÚBLICAS', '2 Política econômica e fiscal.', '2.6 Reformas administrativa e previdenciária e seus impactos fiscais.'),
  ('FINANÇAS PÚBLICAS', '3 Orçamento público.', '3.1 Conceito, técnicas e princípios orçamentários.'),
  ('FINANÇAS PÚBLICAS', '3 Orçamento público.', '3.2 Ciclo e processo orçamentários.'),
  ('FINANÇAS PÚBLICAS', '4 Orçamento público no Brasil.', '4.1 Sistema de planejamento e orçamento.'),
  ('FINANÇAS PÚBLICAS', '4 Orçamento público no Brasil.', '4.2 Plano plurianual, lei de diretrizes orçamentárias e lei orçamentária anual.'),
  ('FINANÇAS PÚBLICAS', '4 Orçamento público no Brasil.', '4.3 Sistema e processo de orçamentação.'),
  ('FINANÇAS PÚBLICAS', '4 Orçamento público no Brasil.', '4.4 Classificações orçamentárias e estrutura programática.'),
  ('FINANÇAS PÚBLICAS', '4 Orçamento público no Brasil.', '4.5 Créditos ordinários e adicionais.'),
  ('FINANÇAS PÚBLICAS', '5 Programação e execução orçamentária e financeira.', '5.1 Descentralização orçamentária e financeira.'),
  ('FINANÇAS PÚBLICAS', '5 Programação e execução orçamentária e financeira.', '5.2 Acompanhamento e controle da execução.'),
  ('FINANÇAS PÚBLICAS', '5 Programação e execução orçamentária e financeira.', '5.3 Sistemas de informações.'),
  ('FINANÇAS PÚBLICAS', '5 Programação e execução orçamentária e financeira.', '5.4 Alterações orçamentárias e créditos adicionais.'),
  ('FINANÇAS PÚBLICAS', '7 Despesa pública: conceito, classificações e estágios.', '7.1 Restos a pagar.'),
  ('FINANÇAS PÚBLICAS', '7 Despesa pública: conceito, classificações e estágios.', '7.2 Despesas de exercícios anteriores.'),
  ('FINANÇAS PÚBLICAS', '7 Despesa pública: conceito, classificações e estágios.', '7.3 Dívidas flutuante e fundada.'),
  ('FINANÇAS PÚBLICAS', '7 Despesa pública: conceito, classificações e estágios.', '7.4 Suprimento de fundos.'),
  ('FINANÇAS PÚBLICAS', '7 Despesa pública: conceito, classificações e estágios.', '7.5 Ordenador de despesa: conceito, ordenador primário e delegação de competência.'),
  ('FINANÇAS PÚBLICAS', '8 Responsabilidade e controle fiscal.', '8.1 Lei Complementar nº 101/2000 e suas alterações (Lei de Responsabilidade Fiscal).'),
  ('FINANÇAS PÚBLICAS', '8 Responsabilidade e controle fiscal.', '8.2 Lei nº 4.320/1964 e suas alterações.'),
  ('FINANÇAS PÚBLICAS', '8 Responsabilidade e controle fiscal.', '8.3 SIAFI (Sistema Integrado de Administração Financeira).'),
  ('FINANÇAS PÚBLICAS', '9 Fluxo de caixa.', '9.1 Elaboração, apresentação, projeção e análise.'),
  ('FINANÇAS PÚBLICAS', '9 Fluxo de caixa.', '9.2 Fluxos de caixa descontados.'),
  ('FINANÇAS PÚBLICAS', '9 Fluxo de caixa.', '9.3 Valor presente líquido (VPL) e taxa interna de retorno (TIR).'),
  ('FINANÇAS PÚBLICAS', '9 Fluxo de caixa.', '9.4 Valores antecipados e postecipados; valor presente e valor futuro; taxa de juros e prazo.'),
  ('FINANÇAS PÚBLICAS', '10 Moeda, crédito e Sistema Financeiro Nacional.', '10.1 Conceitos e funções da moeda.'),
  ('FINANÇAS PÚBLICAS', '10 Moeda, crédito e Sistema Financeiro Nacional.', '10.2 Base monetária, meios de pagamento e multiplicador monetário.'),
  ('FINANÇAS PÚBLICAS', '10 Moeda, crédito e Sistema Financeiro Nacional.', '10.3 Banco Central e instrumentos de controle monetário.'),
  ('FINANÇAS PÚBLICAS', '10 Moeda, crédito e Sistema Financeiro Nacional.', '10.4 Estrutura e instituições do Sistema Financeiro Nacional.'),
  ('FINANÇAS PÚBLICAS', '12 Mercado financeiro brasileiro.', '12.1 Dinâmica e instituições.'),
  ('FINANÇAS PÚBLICAS', '12 Mercado financeiro brasileiro.', '12.2 Mercados primário e secundário e bolsas de valores.'),
  ('FINANÇAS PÚBLICAS', '12 Mercado financeiro brasileiro.', '12.3 Operações à vista, contratos a termo, contratos futuros e mercado de opções.'),
  ('INTELIGÊNCIA ARTIFICIAL', '6 Inteligência artificial generativa.', '6.1 Modelos de linguagem de grande escala – LLM.'),
  ('INTELIGÊNCIA ARTIFICIAL', '6 Inteligência artificial generativa.', '6.2 Geração aumentada por recuperação – RAG.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '1 Modelagem de processos de negócio.', '1.1 Conceitos básicos.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '1 Modelagem de processos de negócio.', '1.2 Identificação e delimitação de processos de negócio.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '1 Modelagem de processos de negócio.', '1.3 Técnicas de mapeamento de processos (modelos AS-IS e TO-BE).'),
  ('DESENVOLVIMENTO DE SISTEMAS', '4 Arquitetura de software.', '4.1 Arquitetura de aplicações web em modelo de três camadas.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '4 Arquitetura de software.', '4.2 Domain-driven design (DDD).'),
  ('DESENVOLVIMENTO DE SISTEMAS', '4 Arquitetura de software.', '4.3 Arquitetura orientada a serviços (SOA).'),
  ('DESENVOLVIMENTO DE SISTEMAS', '4 Arquitetura de software.', '4.4 Arquitetura de microsserviços.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '7 Desenvolvimento.', '7.1 Linguagem Java.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '7 Desenvolvimento.', '7.2 Linguagem JavaScript.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '9 Segurança no desenvolvimento.', '9.1 Práticas de programação segura e revisão de código.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '9 Segurança no desenvolvimento.', '9.2 Melhores práticas de codificação segura OWASP.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '10 Conceitos avançados em engenharia e arquitetura de software.', '10.1 Arquitetura orientada a eventos.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '10 Conceitos avançados em engenharia e arquitetura de software.', '10.2 Mensageria.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '10 Conceitos avançados em engenharia e arquitetura de software.', '10.3 Transações distribuídas e teorema CAP.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '10 Conceitos avançados em engenharia e arquitetura de software.', '10.4 Gerenciamento de identidades com OAuth 2.0 e JWT.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '10 Conceitos avançados em engenharia e arquitetura de software.', '10.5 API gateways.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '1 Infraestrutura em nuvem.', '1.1 Nuvens pública e privada; IaaS, PaaS, SaaS e workloads.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '1 Infraestrutura em nuvem.', '1.2 Estratégias de migração de aplicações, computação serverless e modelo de responsabilidade compartilhada.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '1 Infraestrutura em nuvem.', '1.3 Contêineres e orquestração: Docker, Podman e Kubernetes.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '3 Gestão de serviços.', '3.1 Conceitos e práticas.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '3 Gestão de serviços.', '3.2 ITIL v4: controle de mudanças; gerenciamento de liberação, incidentes e problemas; service desk.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '4 Forense computacional.', '4.1 Preservação de evidências, hash de arquivos e cadeia de custódia.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '4 Forense computacional.', '4.2 Coleta, espelhamento e imagem de discos.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '4 Forense computacional.', '4.3 Técnicas antiforense: criptografia e esteganografia.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '4 Forense computacional.', '4.4 Sanitização de discos e wipe.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '5 Redes de computadores.', '5.1 Firewall e web application firewall (WAF).'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '5 Redes de computadores.', '5.2 Proxy e proxy reverso.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '5 Redes de computadores.', '5.3 DNS.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '5 Redes de computadores.', '5.4 Redes MPLS e SD-WAN.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '5 Redes de computadores.', '5.5 Segmentação e microssegmentação de redes.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.1 Gestão de segurança da informação e continuidade do negócio.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.2 Gestão de identidade e acesso.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.3 Gestão de riscos de segurança da informação.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.4 Arquitetura zero trust.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.5 Identificação, análise e correção de vulnerabilidades.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.6 Ataques em redes e aplicações corporativas e medidas de proteção.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.7 Segurança de endpoints.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.8 Avaliação e testes de segurança em infraestrutura, redes e aplicações.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.9 Infraestrutura de chaves públicas e certificação digital.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '6 Segurança da informação.', '6.10 Prevenção e tratamento de incidentes de segurança da informação.'),
  ('CIÊNCIA DE DADOS', '1 Dado, informação, conhecimento e inteligência.', '1.1 Dados estruturados e não estruturados.'),
  ('CIÊNCIA DE DADOS', '1 Dado, informação, conhecimento e inteligência.', '1.2 Dados abertos.'),
  ('CIÊNCIA DE DADOS', '3 Bancos de dados relacionais.', '3.1 Conceitos e características.'),
  ('CIÊNCIA DE DADOS', '3 Bancos de dados relacionais.', '3.2 Metadados, tabelas, visões, índices, chaves e relacionamentos.'),
  ('CIÊNCIA DE DADOS', '6 Processo de ciência de dados.', '6.1 Modelo de referência CRISP-DM.'),
  ('CIÊNCIA DE DADOS', '6 Processo de ciência de dados.', '6.2 Técnicas de préprocessamento de dados.'),
  ('CIÊNCIA DE DADOS', '8 Mineração de dados.', '8.1 Classificação.'),
  ('CIÊNCIA DE DADOS', '8 Mineração de dados.', '8.2 Regras de associação.'),
  ('CIÊNCIA DE DADOS', '8 Mineração de dados.', '8.3 Regressão.'),
  ('CIÊNCIA DE DADOS', '8 Mineração de dados.', '8.4 Análise de agrupamentos (clusterização).'),
  ('CIÊNCIA DE DADOS', '8 Mineração de dados.', '8.5 Detecção de anomalias.'),
  ('CIÊNCIA DE DADOS', '8 Mineração de dados.', '8.6 Modelagem preditiva.')
) AS x(disciplina_nome, unidade_nome, nome) ON upper(x.disciplina_nome) = upper(disc.nome) AND x.unidade_nome = u.nome

UNION ALL

SELECT disc.id, NULL, x.nome
FROM disc
JOIN (VALUES
  ('MATEMÁTICA FINANCEIRA', '1 Regra de três simples e composta, proporcionalidades e porcentagens.'),
  ('MATEMÁTICA FINANCEIRA', '2 Juros simples e compostos.'),
  ('MATEMÁTICA FINANCEIRA', '3 Capitalização e desconto.'),
  ('MATEMÁTICA FINANCEIRA', '4 Taxas de juros nominal, efetiva, equivalente, real e aparente.'),
  ('MATEMÁTICA FINANCEIRA', '5 Rendas uniformes e variáveis.'),
  ('MATEMÁTICA FINANCEIRA', '7 Cálculo financeiro (Custo real e efetivo das operações de financiamento, empréstimo e investimento.)'),
  ('MATEMÁTICA FINANCEIRA', '8 Avaliação econômica de projetos.'),
  ('MATEMÁTICA FINANCEIRA', '9 Taxas de retorno e taxas internas de retorno.'),
  ('DIREITO CONSTITUCIONAL', '1 Constituição da República Federativa do Brasil de 1988.'),
  ('DIREITO CONSTITUCIONAL', '3 Direitos e garantias fundamentais (Direitos e deveres individuais e coletivos, direitos sociais, direitos de nacionalidade, direitos políticos, partidos políticos.)'),
  ('DIREITO CONSTITUCIONAL', '4 Organização político-administrativa do Estado (Estado federal brasileiro, União, estados, Distrito Federal, municípios e territórios.)'),
  ('DIREITO CONSTITUCIONAL', '5 Administração pública (Disposições gerais, servidores públicos.)'),
  ('DIREITO CONSTITUCIONAL', '6 Poder Executivo (Atribuições e responsabilidades do presidente da República.)'),
  ('DIREITO CONSTITUCIONAL', '8 Poder Judiciário (Disposições gerais.)'),
  ('DIREITO CONSTITUCIONAL', '11 Ordem econômica e financeira.'),
  ('DIREITO CONSTITUCIONAL', '12 Finanças públicas.'),
  ('DIREITO ADMINISTRATIVO', '11 Processo administrativo.'),
  ('DIREITO ADMINISTRATIVO', '13 Crimes contra a Administração Pública previstos no Código Penal.'),
  ('CONTABILIDADE GERAL', '1 Conceitos, objetivos e finalidades da contabilidade.'),
  ('CONTABILIDADE GERAL', '2 Patrimônio: componentes, equação fundamental do patrimônio, situação líquida, representação gráfica.'),
  ('CONTABILIDADE GERAL', '3 Atos e fatos administrativos: conceitos, fatos permutativos, modificativos e mistos.'),
  ('CONTABILIDADE GERAL', '4 Contas: conceitos, contas de débitos, contas de créditos e saldos.'),
  ('CONTABILIDADE GERAL', '5 Plano de contas: conceitos, elenco de contas, função e funcionamento das contas.'),
  ('CONTABILIDADE GERAL', '6 Escrituração: conceitos, lançamentos contábeis, elementos essenciais, fórmulas de lançamentos, livros de escrituração, métodos e processos, regime de competência e regime de caixa.'),
  ('CONTABILIDADE GERAL', '7 Contabilização de operações contábeis diversas: juros, descontos, tributos, aluguéis, variação monetária/cambial, folha de pagamento, compras, vendas e provisões, depreciações e baixa de bens.'),
  ('CONTABILIDADE GERAL', '8 Balancete de verificação: conceitos, modelos e técnicas de elaboração.'),
  ('CONTABILIDADE GERAL', '9 Balanço patrimonial: conceitos, objetivo, composição.'),
  ('CONTABILIDADE GERAL', '10 Demonstração de resultado de exercício: conceito, objetivo, composição.'),
  ('CONTABILIDADE GERAL', '11 Normas Brasileiras de Contabilidade.'),
  ('DIREITO TRIBUTÁRIO', '1 Sistema Tributário Nacional. Princípios Gerais. Limitações do Poder de Tributar.'),
  ('DIREITO TRIBUTÁRIO', '2 Direito tributário. Conceito e princípios.'),
  ('DIREITO TRIBUTÁRIO', '3 Tributos: conceito e espécies. Impostos. Taxas. Contribuição de Melhoria. Imunidades. Impostos da União. Impostos dos estados e do Distrito Federal. Impostos dos municípios.'),
  ('DIREITO TRIBUTÁRIO', '4 Repartição das receitas tributárias.'),
  ('DIREITO TRIBUTÁRIO', '5 Código Tributário Nacional. Competência tributária e suas limitações. Normas gerais de direito tributário. Norma tributária: espécies; vigência e aplicação; interpretação e integração; natureza.'),
  ('DIREITO TRIBUTÁRIO', '6 Obrigação tributária: conceito; espécies; fato gerador (hipótese de incidência); sujeitos ativo e passivo; solidariedade; capacidade tributária; domicílio tributário.'),
  ('DIREITO TRIBUTÁRIO', '7 Responsabilidade tributária. Responsabilidade dos Sucessores. Solidariedade e sucessão. Responsabilidade pessoal e de terceiros. Responsabilidade por infrações. Responsabilidade supletiva.'),
  ('DIREITO TRIBUTÁRIO', '8 Crédito tributário: conceito; natureza; lançamento e suas modalidades; revisão, suspensão, extinção e exclusão; prescrição e decadência; repetição do indébito.'),
  ('DIREITO TRIBUTÁRIO', '9 Garantias e privilégios do crédito tributário.'),
  ('DIREITO TRIBUTÁRIO', '10 Administração Tributária. Fiscalização. Sigilo Fiscal. Dívida Ativa. Certidões Negativas.'),
  ('DIREITO TRIBUTÁRIO', '11 Lei Complementar nº 118, de 2005.'),
  ('DIREITO TRIBUTÁRIO', '12 Crimes contra a ordem tributária (Lei nº 8.137/1990 e suas alterações).'),
  ('ESTATÍSTICA E PROBABILIDADE', '1 Estatística descritiva.'),
  ('ESTATÍSTICA E PROBABILIDADE', '2 Análise exploratória de dados (Gráficos, diagramas, tabelas, medidas descritivas (posição, dispersão, assimetria e curtose).)'),
  ('ESTATÍSTICA E PROBABILIDADE', '4 Amostragem (Amostragem aleatória simples, estratificada, sistemática e por conglomerados.)'),
  ('CONTABILIDADE PÚBLICA', '1 Conceituação, objeto e campo de aplicação.'),
  ('CONTABILIDADE PÚBLICA', '6 Tratamento contábil aplicável aos impostos e contribuições.'),
  ('CONTABILIDADE PÚBLICA', '8 Plano de Contas Aplicado ao Setor Público – PCASP.'),
  ('CONTABILIDADE PÚBLICA', '10 Transações no setor público.'),
  ('CONTABILIDADE PÚBLICA', '11 Normas Brasileiras de Contabilidade Aplicadas ao Setor Público – NBC TSP.'),
  ('CONTABILIDADE PÚBLICA', '12 Manual de Contabilidade Aplicada ao Setor Público – MCASP, 11ª edição.'),
  ('CONTABILIDADE PÚBLICA', '13 Regime contábil.'),
  ('ECONOMIA', '1 Introdução aos problemas econômicos: escassez e escolha; curva de possibilidades de produção; fatores de produção; produtividade e remuneração dos fatores; livre mercado; papel do governo em uma economia em desenvolvimento.'),
  ('ECONOMIA', '2 Microeconomia: oferta e demanda; elasticidades; teoria da produção; custos; concorrência perfeita; monopólio; eficiência econômica; bens públicos e falhas de mercado.'),
  ('ECONOMIA', '3 Macroeconomia: contas nacionais; produto e renda; agregados macroeconômicos; consumo, poupança e investimento; multiplicador; setor público; políticas de estabilização.'),
  ('FINANÇAS PÚBLICAS', '6 Receita pública: conceito, classificações, estágios, fontes e dívida ativa.'),
  ('FINANÇAS PÚBLICAS', '11 Setor externo: balanço de pagamentos, equilíbrio e desequilíbrio, taxas de câmbio e regimes cambiais fixos e flexíveis.'),
  ('LEGISLAÇÃO TRIBUTÁRIA ESTADUAL', '1 Lei Estadual nº 5.900/1996 (ICMS), e suas alterações.'),
  ('LEGISLAÇÃO TRIBUTÁRIA ESTADUAL', '2 Lei Estadual nº 6.555/2004 (IPVA), e suas alterações.'),
  ('LEGISLAÇÃO TRIBUTÁRIA ESTADUAL', '3 Lei Estadual nº 5.077/1989 (ITCD), e suas alterações.'),
  ('LEGISLAÇÃO TRIBUTÁRIA ESTADUAL', '4 Lei Estadual nº 6.771/2006 (Processo Administrativo Tributário), e suas alterações.'),
  ('LEGISLAÇÃO TRIBUTÁRIA ESTADUAL', '5 Lei Estadual nº 8.085/2018 (Programa Contribuinte Arretado), e suas alterações.'),
  ('INTELIGÊNCIA ARTIFICIAL', '1 Fundamentos de inteligência artificial (Relações entre inteligência artificial, aprendizado de máquina e deep learning.)'),
  ('INTELIGÊNCIA ARTIFICIAL', '2 Redes neurais artificiais.'),
  ('INTELIGÊNCIA ARTIFICIAL', '3 Deep learning.'),
  ('INTELIGÊNCIA ARTIFICIAL', '4 Processamento de linguagem natural (Mineração de texto.)'),
  ('INTELIGÊNCIA ARTIFICIAL', '5 Visão computacional.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '2 Metodologias ágeis de desenvolvimento de software: XP, Scrum e Kanban.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '3 Integração contínua e entrega contínua.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '5 Soluções de integração entre sistemas (API REST.)'),
  ('DESENVOLVIMENTO DE SISTEMAS', '6 Testes de software: testes unitários, testes de integração e TDD.'),
  ('DESENVOLVIMENTO DE SISTEMAS', '8 Ferramentas de versionamento Git.'),
  ('INFRAESTRUTURA DE TIC E SEGURANÇA DA INFORMAÇÃO', '2 DevOps e DevSecOps: conceitos, práticas e ferramentas.'),
  ('REFORMA TRIBUTÁRIA', '1 Emenda Constitucional nº 132/2023.'),
  ('REFORMA TRIBUTÁRIA', '2 Lei Complementar nº 214/2025.'),
  ('REFORMA TRIBUTÁRIA', '3 Lei Complementar nº 227/2026.'),
  ('REFORMA TRIBUTÁRIA', '4 Resolução CGIBS nº 6/2026, alterada pela Resolução CGIBS nº 13/2026 (Regulamento do IBS).'),
  ('REFORMA TRIBUTÁRIA', '5 IBS, CBS e Imposto Seletivo.'),
  ('REFORMA TRIBUTÁRIA', '6 Princípio do destino.'),
  ('REFORMA TRIBUTÁRIA', '7 Incidência, não incidência, imunidades, fato gerador, base de cálculo, alíquotas e sujeição passiva.'),
  ('REFORMA TRIBUTÁRIA', '8 Não cumulatividade e apropriação de créditos.'),
  ('REFORMA TRIBUTÁRIA', '9 Extinção dos débitos, ressarcimento e pagamento indevido.'),
  ('REFORMA TRIBUTÁRIA', '10 Importação e exportação.'),
  ('REFORMA TRIBUTÁRIA', '11 Cashback e Cesta Básica Nacional.'),
  ('REFORMA TRIBUTÁRIA', '12 Regimes diferenciados e específicos.'),
  ('REFORMA TRIBUTÁRIA', '13 Administração Tributária e Comitê Gestor do IBS.'),
  ('REFORMA TRIBUTÁRIA', '14 Processo Administrativo Tributário do IBS.'),
  ('REFORMA TRIBUTÁRIA', '15 Distribuição do produto da arrecadação do IBS.'),
  ('REFORMA TRIBUTÁRIA', '16 Regras de transição do IBS, CBS e ICMS.'),
  ('REFORMA TRIBUTÁRIA', '17 Split payment.'),
  ('REFORMA TRIBUTÁRIA', '18 Apuração assistida.'),
  ('REFORMA TRIBUTÁRIA', '19 Sistema Nacional de Gestão de Informações Territoriais (Sinter) e Cadastro Imobiliário Brasileiro (CIB).'),
  ('REFORMA TRIBUTÁRIA', '20 Tabela de Código de Crédito Presumido do IBS e CBS (cCredPres).'),
  ('REFORMA TRIBUTÁRIA', '21 Novas obrigações acessórias: DeRE, Nota Fiscal de Alienação de Bens Imóveis (NF-ABI), Nota Fiscal de Água e Saneamento (NFAg), Bilhete de Passagem Eletrônico Aéreo (BP-e Aéreo), Nota Fiscal de Gás (NF-e Gás) e declarações e documentos fiscais das plataformas digitais.'),
  ('AUDITORIA FISCAL', '1 Sistema Público de Escrituração Digital (SPED).'),
  ('AUDITORIA FISCAL', '2 Manual de Orientação ao Contribuinte da NF-e e NFC-e (MOC – versão 7.0).'),
  ('AUDITORIA FISCAL', '3 Guia Prático da EFD ICMS/IPI (versão 3.2.2).'),
  ('AUDITORIA FISCAL', '4 Manual de Orientação ao Contribuinte do CT-e e CT-e OS (versão 4.0).'),
  ('AUDITORIA FISCAL', '5 Manual de Orientação ao Contribuinte do MDF-e (versão 3.0b).'),
  ('AUDITORIA FISCAL', '6 Tabelas nacionais CFOP, CST, CSOSN e cBenef.'),
  ('AUDITORIA FISCAL', '7 Cruzamento e consistência entre documentos fiscais eletrônicos e EFD ICMS/IPI.'),
  ('AUDITORIA FISCAL', '8 Identificação de omissão de receitas, divergências de escrituração, créditos indevidos e inconsistências fiscais.'),
  ('CIÊNCIA DE DADOS', '2 Coleta, tratamento, armazenamento, integração e recuperação de dados.'),
  ('CIÊNCIA DE DADOS', '4 Modelagem relacional, dimensional e multidimensional.'),
  ('CIÊNCIA DE DADOS', '5 Planilhas e SQL.'),
  ('CIÊNCIA DE DADOS', '7 Visualização e análise exploratória de dados.'),
  ('CIÊNCIA DE DADOS', '9 Aprendizado de máquina: fundamentos, principais algoritmos e métricas de desempenho.'),
  ('CIÊNCIA DE DADOS', '10 Big Data: conceitos, premissas e aplicações.'),
  ('CIÊNCIA DE DADOS', '11 Business Intelligence.')
) AS x(disciplina_nome, nome) ON upper(x.disciplina_nome) = upper(disc.nome);

COMMIT;